[tools]
bat = "latest"
eza = "latest"
helm = "3.17.4"
just = "latest"
krew = "0.4.5"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
postgres = "17.5"
python = "latest"
starship = "latest"
task = "latest"
usage = "2.1.1"
uv = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
