[tools]
bat = "latest"
eza = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
python = "latest"
starship = "latest"
usage = "2.1.1"
uv = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
